services:
  teslamate:
    image: teslamate/teslamate:3.0@sha256:6569026b73bd657455bbec05965d07fa30b6d4d70eaab0bd5b343231c0429167
    restart: unless-stopped
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - MQTT_HOST=${MQTT_HOST}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:18@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql

  grafana:
    image: teslamate/grafana:3.0@sha256:e02d1f036dd10771ea04db2bafc483067a9dbb874d0b5137dda5a6fe539b77dc
    restart: unless-stopped
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./Teslamate-CustomGrafanaDashboards/customdashboards.yml:/etc/grafana/provisioning/dashboards/customdashboards.yml
      - ./Teslamate-CustomGrafanaDashboards/dashboards:/TeslamateCustomDashboards

  mosquitto:
    image: eclipse-mosquitto:2@sha256:9cfdd46ad59f3e3e5f592f6baf57ab23e1ad00605509d0f5c1e9b179c5314d87
    restart: unless-stopped
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto_conf:/mosquitto/config
      - mosquitto_data:/mosquitto/data

  abrp:
    image: fetzu/teslamate-abrp:3.4.0@sha256:ec07409508be4683cb464c54d5e8884558e9eed09924cdf036fa2c1d49bb8f9d
    init: true
    restart: unless-stopped
    environment:
      - MQTT_SERVER=${MQTT_HOST}
      - USER_TOKEN=${USER_TOKEN}
      - CAR_NUMBER=${CAR_NUMBER}
      - CAR_MODEL=${CAR_MODEL}

volumes:
  postgres_data:
  grafana_data:
  mosquitto_conf:
  mosquitto_data:
