services:
  teslamate:
    image: teslamate/teslamate:4.0.1@sha256:e77ec65007aafb40d736ed2c89675112fe8d960886ea9d7de3255f2b5360269f
    restart: unless-stopped
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - MQTT_HOST=${MQTT_HOST}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:18@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql

  grafana:
    image: teslamate/grafana:4.0.1@sha256:f2afcd9bdc849e65ef53c765be8590a0f0f8416709f501aa179760ea97035cf8
    restart: unless-stopped
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./Teslamate-CustomGrafanaDashboards/customdashboards.yml:/etc/grafana/provisioning/dashboards/customdashboards.yml
      - ./Teslamate-CustomGrafanaDashboards/dashboards:/TeslamateCustomDashboards

  mosquitto:
    image: eclipse-mosquitto:2@sha256:6f8d8a947c506f8a2290ec65cd4bd2bc7cb4d43fb5f6271f861cb013e2ef9797
    restart: unless-stopped
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto_conf:/mosquitto/config
      - mosquitto_data:/mosquitto/data

  abrp:
    image: fetzu/teslamate-abrp:4.0.0@sha256:605cbfa86aeda5a4f5cfcc4f05e4483a199abbbc0498924c0cad7a00c5e59d5a
    init: true
    restart: unless-stopped
    environment:
      - MQTT_SERVER=${MQTT_HOST}
      - USER_TOKEN=${USER_TOKEN}
      - CAR_NUMBER=${CAR_NUMBER}
      - CAR_MODEL=${CAR_MODEL}

volumes:
  postgres_data:
  grafana_data:
  mosquitto_conf:
  mosquitto_data:
