services:
  homeassistant:
    image: homeassistant/home-assistant:2026.6@sha256:adb3341e31e03e0048e60d8c1cf952e118a381ae258bb921d3da12a3b27bf0c2
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Berlin
    network_mode: host
    volumes:
      - ./config:/config
      - ./config/docker/run:/etc/services.d/home-assistant/run
    depends_on:
      database:
        condition: service_healthy
        restart: true

  database:
    image: timescale/timescaledb-ha:pg18-ts2.28@sha256:5942884232a38a3449c581a44ca1620abcfc8c113e7ab7def9acfd95015aaee6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/home/postgres/pgdata
    shm_size: 1gb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]

  grafana:
    image: grafana/grafana:13.0@sha256:5dad0df181cb644a14e13617b913b261a54f7d4fd4510721dba420929f35bea2
    restart: unless-stopped
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - 3001:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      database:
        condition: service_healthy
        restart: true

volumes:
  postgres_data:
  grafana_data:
